# Generated by Django 3.2.4 on 2021-09-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbers',
            name='name',
        ),
    ]
